"""Offline, self-contained HTML index. JSON is data, never executable markup."""
import json


def render(session):
    calls={name:json.loads((session.root/name).read_text()) for name in session.assets
        if name.startswith("calls/") and name.endswith(".json")}
    data=json.dumps({"metadata":session.metadata,"events":session.events,"calls":calls},ensure_ascii=False).replace("<","\\u003c")
    return HTML.replace("__SESSION_DATA__",data)


HTML=r'''<!doctype html><html lang="en"><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Session replay · Adapter v1</title>
<style>
:root{font-family:system-ui,sans-serif;color:#193b39;background:#f3f4ef}body{max-width:1480px;margin:0 auto;padding:28px}h1{margin:5px 0;font-size:30px}h2{font-size:17px;margin:0 0 12px}p{margin:8px 0}.muted{color:#637774}header{display:flex;justify-content:space-between;align-items:center;gap:20px}.badge{background:#dbe9df;border-radius:20px;padding:8px 16px;font-weight:600}button,select,input{font:inherit}button,select{border:1px solid #b6c9c0;border-radius:7px;background:white;padding:7px 12px;color:#234741;cursor:pointer}button:hover{background:#e5eee6}.panel{background:#fff;border:1px solid #d5dfd8;border-radius:12px;padding:18px;margin-top:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.grid .panel{min-width:0;margin-top:0}.scene{width:100%;height:300px;object-fit:contain;background:#eef2eb;image-rendering:pixelated}.controls{display:flex;gap:12px;align-items:center;margin:12px 0}.controls input{flex:1;min-width:100px}.lane{display:grid;grid-template-columns:110px 1fr;align-items:center;margin:13px 0}.track{height:32px;background:#edf2ec;border-radius:6px;position:relative}.dot{position:absolute;width:9px;height:26px;top:3px;border-radius:3px;cursor:pointer;background:#328372}.dot.brain{background:#365faf}.dot.controller{background:#c7703c}.dot.execution{background:#368273}pre{font:12px/1.5 ui-monospace,monospace;white-space:pre-wrap;word-break:break-word;max-height:300px;overflow:auto;background:#f5f6f2;border-radius:8px;padding:12px}summary{cursor:pointer;margin:10px 0;color:#305f87}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;border-bottom:1px solid #e2e8e1;padding:9px}tr.pick{cursor:pointer}tr.pick:hover,tr.active{background:#edf4ec}.scroll{max-height:340px;overflow:auto}#clock{font-variant-numeric:tabular-nums}a{color:#316e8e}.warn{color:#a04c25}#inspection{font-size:14px}@media(max-width:850px){body{padding:14px}.grid{grid-template-columns:1fr}header{display:block}.badge{display:inline-block}.scene{height:240px}.lane{grid-template-columns:90px 1fr}}
</style>
<header><div><p class="muted">GAME SESSION / THREE SYNCHRONIZED TIMELINES</p><h1 id="title"></h1><p id="subtitle" class="muted"></p></div><div class="badge" id="status"></div></header>
<section class="panel"><h2>Frame clock · planner ideas · controller decisions</h2><p class="muted">Select a decision to inspect its exact observation, plan, model response and execution. No network or running services required.</p><div id="lanes"></div><div class="controls"><button id="prev">← Decision</button><button id="play">Play frames</button><button id="next">Decision →</button><select id="speed"><option value="1">1× game time</option><option value="0.25">0.25× game time</option></select></div><div class="controls"><input id="frame" type="range" min="0" value="0"><span id="clock"></span></div><p id="inspection" class="muted"></p></section>
<div class="grid"><section class="panel"><h2>Observed frame</h2><img class="scene" id="scene" alt="Recorded game frame"><p id="image-note" class="muted"></p><pre id="state"></pre></section>
<section class="panel"><h2>Motor skill → exact inputs → actual execution</h2><p class="muted">Names describe control intent, not guaranteed outcomes. Interrupted tails are discarded, never silently resumed.</p><pre id="motor-program"></pre><pre id="execution"></pre><details><summary>Session metadata / versions / provenance</summary><pre id="metadata"></pre></details></section>
<section class="panel"><h2>Brain · ordered intentions, not action permissions</h2><h2>Current goal / upcoming goals / evidence</h2><pre id="intent"></pre><details><summary>Full plan + global guidance</summary><pre id="plan"></pre></details><details open><summary>Provider-returned response</summary><pre id="brain-output"></pre></details><details><summary>Exact recorded request</summary><pre id="brain-input"></pre></details></section>
<section class="panel"><h2>Controller · Jev / local model / declared backend</h2><pre id="choice"></pre><details open><summary>Provider-returned response</summary><pre id="controller-output"></pre></details><details><summary>Exact recorded request + candidate actions</summary><pre id="controller-input"></pre></details></section></div>
<section class="panel"><h2>Decision index</h2><div class="scroll"><table><thead><tr><th>Decision</th><th>Frames</th><th>Plan</th><th>Model choice</th><th>Requested / actual</th><th>Interruption</th></tr></thead><tbody id="decisions"></tbody></table></div></section>
<section class="panel"><h2>Wall-clock event ledger</h2><p class="muted">Click any row to inspect it, including failed calls with no executed decision. Model waits consume wall time, never game frames. “Ideas” are returned plans/rationales, not hidden model thoughts.</p><div class="scroll"><table><thead><tr><th>Seq</th><th>Frame</th><th>Wall seconds</th><th>Event</th><th>Link</th></tr></thead><tbody id="ledger"></tbody></table></div></section>
<section class="panel"><h2>Event / call inspector</h2><p id="call-label" class="muted">Select a ledger event.</p><pre id="event-detail"></pre><div class="grid"><div><h2>Recorded request</h2><pre id="call-input"></pre></div><div><h2>Provider-returned response</h2><pre id="call-output"></pre></div></div></section>
<script type="application/json" id="session-data">__SESSION_DATA__</script>
<script>
const D=JSON.parse(document.getElementById('session-data').textContent),E=D.events,M=D.metadata;
const $=id=>document.getElementById(id),pretty=x=>JSON.stringify(x??null,null,2),put=(id,x)=>$(id).textContent=pretty(x);
const frames=E.filter(e=>e.kind==='frame.executed'||e.kind==='frame.initial'),decisions=E.filter(e=>e.kind==='decision.selected'),plans=E.filter(e=>e.kind==='plan.installed');
const fps=M.profile.fps,last=M.final_frame||0;let chosen=0,timer=null;
$('title').textContent=M.profile.game;$('subtitle').textContent=M.session_id+' · '+M.profile.observation_mode;$('status').textContent=M.stop_reason+' · F'+last;
$('frame').max=last;put('metadata',M);
function cell(row,value){const td=document.createElement('td');td.textContent=value??'—';row.append(td)}
function lane(label,kind,cls){const row=document.createElement('div');row.className='lane';const text=document.createElement('b');text.textContent=label;row.append(text);const track=document.createElement('div');track.className='track';E.filter(e=>e.kind===kind).forEach(e=>{const dot=document.createElement('button');dot.className='dot '+cls;dot.style.padding='0';dot.style.left=(e.frame/Math.max(1,last)*98)+'%';dot.title=`${e.kind} · F${e.frame} · ${(e.wall_ns/1e9).toFixed(3)}s`;dot.setAttribute('aria-label',dot.title);dot.onclick=()=>{if(kind==='plan.installed'){inspectPlan(e);inspectEvent(e)}else{const i=decisions.findIndex(d=>d.decision_id===e.decision_id);if(i>=0)select(i);else inspectEvent(e)}};track.append(dot)});row.append(track);$('lanes').append(row)}
lane('Game frames','execution.started','execution');lane('Brain plans','plan.installed','brain');lane('Decisions','decision.selected','controller');
function showFrame(f){$('frame').value=f;const row=frames.find(r=>r.frame===f)||[...frames].reverse().find(r=>r.frame<=f);$('clock').textContent=`F${f} · ${(f/fps).toFixed(3)}s game`;if(row?.image){$('scene').src=row.image.path;$('scene').style.visibility='visible';$('image-note').textContent=`Recorded post-step frame ${row.frame}`;}else{$('scene').removeAttribute('src');$('scene').style.visibility='hidden';$('image-note').textContent='No valid framebuffer at this snapshot; no frame was invented.'}put('state',row?{frame:row.frame,wall_seconds:row.wall_ns/1e9,input:row.input_buttons,metrics:row.metrics,events:row.game_events,terminal:row.terminal}:null)}
function inspectPlan(p){showFrame(p.frame);put('plan',p.plan);put('intent',p.intent_queue);put('motor-program',null);put('brain-input',D.calls[`calls/${p.call_id}/request.json`]);put('brain-output',D.calls[`calls/${p.call_id}/response.json`]);for(const id of ['choice','execution','controller-input','controller-output'])put(id,null);$('inspection').textContent=`Inspecting ${p.plan_id} at F${p.frame}; no controller decision selected.`;Array.from($('decisions').children).forEach(r=>r.className='pick')}
function inspectEvent(e){showFrame(e.frame);put('event-detail',e);$('call-label').textContent=`${e.event_id} · ${e.kind} · ${e.call_id||'no call reference'}`;put('call-input',e.call_id?D.calls[`calls/${e.call_id}/request.json`]:null);put('call-output',e.call_id?(D.calls[`calls/${e.call_id}/response.json`]||{status:'No response recorded; inspect call.failed event. No output was invented.'}):null)}
function select(i){if(!decisions.length){showFrame(0);return}chosen=Math.max(0,Math.min(i,decisions.length-1));const d=decisions[chosen],p=plans.find(p=>p.plan_id===d.plan_id),x=E.find(e=>e.kind==='execution.completed'&&e.decision_id===d.decision_id),beg=E.find(e=>e.kind==='execution.started'&&e.decision_id===d.decision_id);showFrame(d.frame);put('plan',p?.plan);put('intent',d.intent_progress);put('motor-program',beg?.action);put('choice',d);put('execution',x||beg||{status:'selected but never executed'});for(const [role,cid] of [['brain',p?.call_id],['controller',d.call_id]]){put(role+'-input',D.calls[`calls/${cid}/request.json`]);put(role+'-output',D.calls[`calls/${cid}/response.json`])}$('inspection').textContent=`Inspecting ${d.decision_id} · ${d.action_label||d.executor_choice} at F${d.frame} · ${d.plan_id}. Moving the frame slider keeps this decision pinned.`;Array.from($('decisions').children).forEach((r,j)=>r.className=j===chosen?'pick active':'pick')}
decisions.forEach((d,i)=>{const x=E.find(e=>e.kind==='execution.completed'&&e.decision_id===d.decision_id);const row=document.createElement('tr');row.className='pick';[d.decision_id,x?`${x.frame_start} → ${x.frame_end}`:d.frame,d.plan_id,d.model_choice??`${d.executor_choice} (sole candidate; no controller call)`,x?`${x.requested_frames} / ${x.executed_frames}`:'not executed',x?.interruption].forEach(v=>cell(row,v));row.onclick=()=>select(i);$('decisions').append(row)});
E.filter(e=>!e.kind.startsWith('frame.')).forEach(e=>{const row=document.createElement('tr');row.className='pick';[e.seq,e.frame,(e.wall_ns/1e9).toFixed(3),e.kind,e.call_id||e.plan_id||e.execution_id||e.reason||''].forEach(v=>cell(row,v));row.onclick=()=>inspectEvent(e);$('ledger').append(row)});
$('frame').oninput=()=>showFrame(Number($('frame').value));$('prev').onclick=()=>select(chosen-1);$('next').onclick=()=>select(chosen+1);
$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='Play frames';return}if(Number($('frame').value)>=last)showFrame(0);$('play').textContent='Pause';timer=setInterval(()=>{const f=Number($('frame').value);if(f>=last){clearInterval(timer);timer=null;$('play').textContent='Play frames';return}showFrame(f+1)},1000/(fps*Number($('speed').value)))};
select(0);const lastCall=[...E].reverse().find(e=>e.kind==='call.failed');if(lastCall)inspectEvent(lastCall);
</script></html>'''
